import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/AppSidebar";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <SidebarProvider>
            <AppSidebar />
            <main className=" bg-slate-900 w-full">
              <SidebarTrigger className="w-fit bg-slate-900" />
              {children}
            </main>
          </SidebarProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
